// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgM0eLfFxHkDJ6T6-h4vUFwRndRYHGKGg',
    appId: '1:397501394788:web:41b4e2e3b7e099b355d471',
    messagingSenderId: '397501394788',
    projectId: 'cockat-a7382',
    authDomain: 'cockat-a7382.firebaseapp.com',
    storageBucket: 'cockat-a7382.firebasestorage.app',
    measurementId: 'G-Q6HBREEK28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLsaANUBrGth5jZL-LbDAIZotFPvE-fTo',
    appId: '1:397501394788:android:381ba70a9888292e55d471',
    messagingSenderId: '397501394788',
    projectId: 'cockat-a7382',
    storageBucket: 'cockat-a7382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnvZ94F8EArWoGKH8kHydsazK2CACeGLY',
    appId: '1:397501394788:ios:26ae28107dec978155d471',
    messagingSenderId: '397501394788',
    projectId: 'cockat-a7382',
    storageBucket: 'cockat-a7382.firebasestorage.app',
    iosBundleId: 'com.cockat.cockat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgM0eLfFxHkDJ6T6-h4vUFwRndRYHGKGg',
    appId: '1:397501394788:web:a480168da96b170455d471',
    messagingSenderId: '397501394788',
    projectId: 'cockat-a7382',
    authDomain: 'cockat-a7382.firebaseapp.com',
    storageBucket: 'cockat-a7382.firebasestorage.app',
    measurementId: 'G-PGW2DMZK19',
  );
}
